'use strict';

module.exports = {
  CANCEL_CHANGES: 'CANCEL_CHANGES',
  SET_DELTA_TEMPLATE: 'SET_DELTA_TEMPLATE',
  SET_DELTA_URL: 'SET_DELTA_URL',
  FETCH_NEW_TEMPLATE: 'FETCH_NEW_TEMPLATE',
  SUBMIT_TEMPLATE: 'SUBMIT_TEMPLATE',
  SET_CONFIG: 'SET_CONFIG'
};
